INTRO = "Benvinguts al servei d'atenció ciutadana. Us informem que aquesta trucada pot ser gravada. Per emergències, truqui al 112. Si és per una altra cosa, digui'm, en què el puc ajudar?"
# "Hola! Em dic Olga i sóc l'assistent virtual del 012 quan ningú el pot atendre. En què el puc ajudar?"
NO_MATCH = "Encara no el puc ajudar a fer això. Pregunti'm per una altra cosa"
USE_GOOGLE_CHROME = "Fantàstic. Estic encantada de poder ajudar-lo, però primer em pot indicar si fa anar Google Crom?"
CHROME_INSTALLED = "Te instal·lada la extensió de Crom de l'assistent virtual Avia?"
NO_CHROME_INSTALLED = "Malauradament no el puc ajudar. Si us plau, posi's en contacte més endavant i l'atendrà un company o una companya"
WHATSAPP_INSTALL = "No es preocupi, ara li envio un WhatsApp amb les instruccions per a fer-ho."
START_FLOW = "Perfecte, ara l'aniré guiant per tot el procés."
